### ISSUE TITLE
Link of 4 pin female wire connector is ambiguous

### ISSUE THREAD

**Issue by yoneken** [PCrnjak/SSG-48-adaptive-electric-gripper#2]
There are several options for 4pin female wire connector of [the current link](https://s.click.aliexpress.com/e/_DCG5Rff).
One is the screw type and another is the welding one.

<img width="292" alt="Angle 4pin female screw" src="https://github.com/user-attachments/assets/6d369e78-08e7-48ec-8637-b252273e3b72">

<img width="292" alt="Angle 4pin female welding" src="https://github.com/user-attachments/assets/9a33bcb2-71f0-45c6-a6c4-1f014ce33f1a">

The outer diameter of the screw type (φ14mm) is bigger than the welding one (φ12mm). And the outer diameter of the screw type interferes with the shell of gripper and does not fit!
We should choose the welding type.

**Comment by PCrnjak** [comment]
Use welding type both for the cables and the gripper

**Comment by yoneken** [comment]
I bought a screw one ;(
